### ISSUE TITLE
Screenshots are not removing legend

### ISSUE THREAD

**Issue by UDS-Furnace** [UDS-Furnace/View#7]
![30-June-22 - 01-45-27 PM](https://user-images.githubusercontent.com/105358746/176743324-0bcd4f11-3e64-47dd-b47c-82c4e5709fc0.png)

Screenshots are showing duplicated legends.

Steps to reproduce:
-View previously recorded charge.
-Open live view.
-Save image.

**Comment by brlnoble** [comment]
Bug has been fixed by properly clearing plot when switching between screens.

https://github.com/brlnoble/DataLoggerProgram/commit/3f679fd0c4078f0af6a994e47e2a4cc38ee9859d
